### ISSUE TITLE
Request for example to read and update status of the leds

### ISSUE THREAD

**Issue by sjoerdboerhout** [WAGO/pfc-howtos#11]
In addition to the example to read the state of the switch it would be useful to have an example how you can read/set the status of the internal status leds of the PLC and print the status to the terminal.

**Comment by damianrudnik** [comment]
you can use script  `/etc/config-tools/get_led_config all-states`
try different parameters:
```
./get_led_config --help

* Get configuration and values of LEDs *

Usage: get_led_config [ parameter ] < [led-name] | [led-number] >

parameter: "xml" | "name" | "state" | "frequency1" | "frequency2" | "diagtext" | "complete-state" | "all-states"  | "all-states-ordered"

led-name:           unique identifier of the LED specified by LED configuration XML-file
led-number:         numeric index of the LED specified by LED configuration XML-file
xml:                prints complete LED configuration XML-file
name:               prints led-name for a given led-number
state:              prints current state for given led-name
frequency1:         prints first part of blink sequence or 0 depending on current state for given led-name
frequency2:         prints second part of blink sequence or 0 depending on current state for given led-name
diagtext:           prints current diagnostic text for given led-name
complete-state:     prints current state, frequency1 & 2 and diagtext for given led-name
all-states:         prints current state, frequency1 & 2 and diagtext for all LEDs
all-states-ordered: prints same information as all-states in logical order of device specific LED groups
```

**Comment by sjoerdboerhout** [comment]
But it looks like this script is only able to retrieve the current values.
For example the RUN led is always off now when I have my own C-application active. Would be nice if we can set the run led when the application is active.
Same for the user leds.

bash-4.4# ./get_led_config all-states       
SYS: GRN 0 0 Wed Jun 23 08:39:38 2021: "System Booted"
RUN: OFF 0 0 Wed Jun 23 08:39:38 2021: "PLC is shut down"
IO: GRN 0 0 Wed Jul 14 14:13:54 2021: "KBus is operational"
MS: OFF 0 0 Wed Jun 23 08:39:38 2021: "no extended error code active"
NS: OFF 0 0 Wed Jun 23 08:39:38 2021: "not active"
CAN: OFF 0 0 Wed Jun 23 08:39:38 2021: "Fieldbus not active"
BF: OFF 0 0 Wed Jun 23 08:39:38 2021: "Fieldbus not active"
DIA: OFF 0 0 Wed Jun 23 08:39:38 2021: "Fieldbus not active"
U1: OFF 0 0 Wed Jun 23 08:39:38 2021: "User LED 1 is turned "off""
U2: OFF 0 0 Wed Jun 23 08:39:38 2021: "User LED 2 is turned "off""
U3: OFF 0 0 Wed Jun 23 08:39:38 2021: "User LED 3 is turned "off""
U4: OFF 0 0 Wed Jun 23 08:39:38 2021: "User LED 4 is turned "off""

**Comment by damianrudnik** [comment]
here you can use this script to set U1-U6 diodes:
```
#!/bin/sh
case $1 in
	green)
		eventmsg 0x40010001
		eventmsg 0x40010101
		eventmsg 0x40010201
		eventmsg 0x40010301
		eventmsg 0x40010401
		eventmsg 0x40010501
		;;
	red)
		eventmsg 0x40010002
		eventmsg 0x40010102
    	        eventmsg 0x40010202
		eventmsg 0x40010302
		eventmsg 0x40010402
		eventmsg 0x40010502
		;;

	yellow)
		eventmsg 0x40010003
		eventmsg 0x40010103
    	        eventmsg 0x40010203
    	        eventmsg 0x40010303
		eventmsg 0x40010403
		eventmsg 0x40010503
		;;

	off)
		eventmsg 0x40010000
		eventmsg 0x40010100
		eventmsg 0x40010200
		eventmsg 0x40010300
		eventmsg 0x40010400
		eventmsg 0x40010500
		;;

	*) 
		echo "Usage: ${0} green|yellow|red|off"
		exit 1
		;;
esac
```

**Comment by sjoerdboerhout** [comment]
Still curious if it is possible to set the RUN led from a custom C/C++ application when it is active.

**Comment by Helmut-Saal** [comment]
If you like to overwrite you can do it.
echo 255 > /dev/leds/run-red/brightness
echo 0 > /dev/leds/run-red/brightness
echo 0 > /dev/leds/run-green/brightness

**Comment by sjoerdboerhout** [comment]
It has nothing to do with 'overwrite'. When I start a custom C-application then the RUN led is never set. I want to do that from the application to have a visual confirmation that the application is up and running. 

Thanks for pointing me to /dev/leds. Very useful!

sjoerd@WAGO8216FW19:~ cd /dev/leds
sjoerd@WAGO8216FW19:/dev/leds ls -al
drwxr-xr-x    2 root     root           540 Sep 30 20:15 .
drwxr-xr-x   10 root     root          3140 Sep 30 20:15 ..
lrwxrwxrwx    1 root     root            32 Sep 30 20:15 bf-green -> /sys/class/leds/pca955x:bf-green
lrwxrwxrwx    1 root     root            30 Sep 30 20:15 bf-red -> /sys/class/leds/pca955x:bf-red
lrwxrwxrwx    1 root     root            33 Sep 30 20:15 can-green -> /sys/class/leds/pca955x:can-green
lrwxrwxrwx    1 root     root            31 Sep 30 20:15 can-red -> /sys/class/leds/pca955x:can-red
lrwxrwxrwx    1 root     root            33 Sep 30 20:15 dia-green -> /sys/class/leds/pca955x:dia-green
lrwxrwxrwx    1 root     root            31 Sep 30 20:15 dia-red -> /sys/class/leds/pca955x:dia-red
lrwxrwxrwx    1 root     root            32 Sep 30 20:15 io-green -> /sys/class/leds/pca955x:io-green
lrwxrwxrwx    1 root     root            30 Sep 30 20:15 io-red -> /sys/class/leds/pca955x:io-red
lrwxrwxrwx    1 root     root            32 Sep 30 20:15 ms-green -> /sys/class/leds/pca955x:ms-green
lrwxrwxrwx    1 root     root            30 Sep 30 20:15 ms-red -> /sys/class/leds/pca955x:ms-red
lrwxrwxrwx    1 root     root            32 Sep 30 20:15 ns-green -> /sys/class/leds/pca955x:ns-green
lrwxrwxrwx    1 root     root            30 Sep 30 20:15 ns-red -> /sys/class/leds/pca955x:ns-red
lrwxrwxrwx    1 root     root            33 Sep 30 20:15 run-green -> /sys/class/leds/pca955x:run-green
lrwxrwxrwx    1 root     root            31 Sep 30 20:15 run-red -> /sys/class/leds/pca955x:run-red
lrwxrwxrwx    1 root     root            33 Sep 30 20:15 sys-green -> /sys/class/leds/pca955x:sys-green
lrwxrwxrwx    1 root     root            36 Sep 30 20:15 sys-over-red -> /sys/class/leds/pca955x:sys-over-red
lrwxrwxrwx    1 root     root            31 Sep 30 20:15 sys-red -> /sys/class/leds/pca955x:sys-red
lrwxrwxrwx    1 root     root            32 Sep 30 20:15 u1-green -> /sys/class/leds/pca955x:u1-green
lrwxrwxrwx    1 root     root            30 Sep 30 20:15 u1-red -> /sys/class/leds/pca955x:u1-red
lrwxrwxrwx    1 root     root            32 Sep 30 20:15 u2-green -> /sys/class/leds/pca955x:u2-green
lrwxrwxrwx    1 root     root            30 Sep 30 20:15 u2-red -> /sys/class/leds/pca955x:u2-red
lrwxrwxrwx    1 root     root            32 Sep 30 20:15 u3-green -> /sys/class/leds/pca955x:u3-green
lrwxrwxrwx    1 root     root            30 Sep 30 20:15 u3-red -> /sys/class/leds/pca955x:u3-red
lrwxrwxrwx    1 root     root            32 Sep 30 20:15 u4-green -> /sys/class/leds/pca955x:u4-green
lrwxrwxrwx    1 root     root            30 Sep 30 20:15 u4-red -> /sys/class/leds/pca955x:u4-red

**Comment by Helmut-Saal** [comment]
If you are not using PLC Runtime it would not "overwrite", but if you use Runtime the Led Server Daemon controlles Leds and then it is "overwrite". Great that it works for you.
