### ISSUE TITLE
Adressing behavior in bit access FC

### ISSUE THREAD

**Issue by quenorha** [WAGO/pfc-howtos#12]
It looks the adressing doesn't exactly match a standard coupler (750-3x2) when using write coil function code.

First example, a configuration with 
- 1 x 750-530 (8DO)
- 1 x 750-504 (4DO)
- 1 x 750-1504 (16DO)
The registers are 512->519 => 750-530
                            520->527 => blank
                            528->531 => 750-504
                            532->536 => First 4 channel of 750-1504
                            537->543 => blank
                            544->551 =>750-1504 5th to 12th channel
                            552->559 => blank
                            560->563 => 750-1504 13th to 16th channel
In bit access, digital outputs should be next to each other. 
There is a blank byte between each byte. 

Second example with 3 x 750-515
                           512->515 => first 750-515
                           516->519 => second 750-515
                           520->527 => blank
                           528->531 => 3rd 750-515

Could you correct it to make it match the behavior of a standard modbus coupler ? Thanks. 
I guess digital inputs are also affected.

**Comment by Thomas-Brandt** [comment]
Hi Quentin,

please check the new docker version.

**Comment by quenorha** [comment]
This issue is still present on 1.5.1 version.

**Comment by quenorha** [comment]
The issue is still present on 1.6.0 version.
