### ISSUE TITLE
Add a how to for installing docker-compose

### ISSUE THREAD

**Issue by jakebjorkekato** [WAGO/pfc-howtos#3]
With the possibility of installing docker from [here](https://github.com/WAGO/docker-ipk) it would be nice to be able to use [docker-compose](https://docs.docker.com/compose/).

I am not sure of the tooling available in the default firmware if `docker-compose` would be supported.

**Comment by DirkMeihoefer** [comment]
Please be patient ;)
We are in the process of creating a docker-compose ipk, which will be published here on GitHub.

**Comment by Helmut-Saal** [comment]
Docker-Compose IPK added for use.

**Comment by jakebjorkekato** [comment]
I was able to get docker-compose running, once I went over to the below repo.

https://github.com/WAGO/docker-compose-ipk

![image](https://user-images.githubusercontent.com/15744759/61329075-10558b80-a7e2-11e9-93c2-9615704c7456.png)

The only note I had from setting up, would to add the `.ipk` as an asset under a release so you don't have to clone or navigate the repo to pull it down

![image](https://user-images.githubusercontent.com/15744759/61328913-b0f77b80-a7e1-11e9-9985-de5024e5da0d.png)

Doing this would also allow us to subscribe to the repo on release-only so we would be notified when there are changes automatically.

If it would be easier we could move this discussion to that repo, and close this issue.

Thank you for putting this together so quickly.

**Comment by DirkMeihoefer** [comment]
The ipk is now available under the releases. Thank you for the hint.

**Comment by justinbyerss** [comment]
Hi guys, I am trying to install docker compose however this link https://github.com/WAGO/docker-compose-ipk doesnt exist anymore.

**Comment by Helmut-Saal** [comment]
Hi, we provide not longer compose as native installer for our devices. Please simple use the compose container on our dockerhub.
https://hub.docker.com/repository/docker/wagoautomation/docker-compose/general

**Comment by robogeek** [comment]
I understand this is an old closed issue.

In my opinion, lacking "Docker Compose" is an extreme hindrance.  Compose is THE way to deploy a multi-container system.  Before a Kubernetes fanboi pops in, of course Kubernetes is completely inappropriate for use on a PLC.  Since it's still necessary to deploy multiple containers as a group, we need an appropriate way to do so, and Compose is the way to go.
