### ISSUE TITLE
Compile error with kbusmodbusslave

### ISSUE THREAD

**Issue by Ekristoffe** [WAGO/pfc-howtos#5]
Hello got some trouble while compiling the kbusmodbusslave found here.
I have followed the how to line by line but I have some trouble:

First the command: 
> user@ubuntu:~/wago/ptxproj$ ptxdist clean kbusmodbusslave
Give me this:
```
'enerated/wago_specific_dal.in:1:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:3:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:4:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:5:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:6:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:7:warning: ignoring unsupported character '
'enerated/wago_specific_dal.in:1:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:3:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:4:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:5:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:6:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:7:warning: ignoring unsupported character '
'enerated/wago_specific_dal.in:1:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:3:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:4:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:5:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:6:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:7:warning: ignoring unsupported character '
'enerated/wago_specific_dal.in:1:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:3:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:4:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:5:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:6:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:7:warning: ignoring unsupported character '

-----------------------------
target: kbusmodbusslave.clean
-----------------------------

rm -rf /home/user/wago/ptxproj/platform-wago-pfcXXX/state/kbusmodbusslave.*
rm -rf /home/user/wago/ptxproj/platform-wago-pfcXXX/packages/kbusmodbusslave_*
rm -rf /home/user/wago/ptxproj/platform-wago-pfcXXX/build-target/kbusmodbusslave
```

Then the command: 
> user@ubuntu:~/wago/ptxproj$ ptxdist targetinstall kbusmodbusslave
Give me:
```
'enerated/wago_specific_dal.in:1:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:3:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:4:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:5:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:6:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:7:warning: ignoring unsupported character '
'enerated/wago_specific_dal.in:1:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:3:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:4:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:5:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:6:warning: ignoring unsupported character '
'home/user/wago/ptxproj/rules/kbusmodbusslave.in:7:warning: ignoring unsupported character '
Package wago_diagnostic was not found in the pkg-config search path.
Perhaps you should add the directory containing `wago_diagnostic.pc'
to the PKG_CONFIG_PATH environment variable
No package 'wago_diagnostic' found
In file included from main.c:27:0:
modbus.h:5:27: fatal error: modbus/modbus.h: No such file or directory
compilation terminated.
make[1]: *** [main.o] Error 1
make: *** [/home/user/wago/ptxproj/platform-wago-pfcXXX/state/kbusmodbusslave.compile] Error 2
```
In the file ptxproj/rules/kbusmodbusslave.in the CRLF must be replaced by only LF to remove the warning of characters.

If anyone have some idea ...

**Comment by Thomas-Brandt** [comment]
Hi Christophe ;)

the kbusmodbusslave.in in this repo don't include <CR>.
Maybe you had a merge conflict with your forked repo. 
And/OR your editor has automatically added the <CR> to your file.

Best Regards 
Thomas

**Comment by Ekristoffe** [comment]
Hello Thomas,
Indeed I have done a git from linux and the file are ok (git under windows brake stuff ?)
But I still have some compile error:
<pre><font color="#729FCF"><b>~/wago/ptxproj</b></font>$ ptxdist targetinstall kbusmodbusslave

---------------------------
target: kbusmodbusslave.get
---------------------------

finished target kbusmodbusslave.get

-------------------------------
target: kbusmodbusslave.extract
-------------------------------

extract: pkg_src=ptxproj/src/kbusmodbusslave-1.3.0.tar.bz2
extract: pkg_extract_dir=ptxproj/platform-wago-pfcXXX/build-target/kbusmodbusslave
patchin: no patches found
finished target kbusmodbusslave.extract

------------------------------------
target: kbusmodbusslave.extract.post
------------------------------------

patchin: fixup:
patchin: fixup: done

finished target kbusmodbusslave.extract.post

-------------------------------
target: kbusmodbusslave.prepare
-------------------------------

finished target kbusmodbusslave.prepare

-------------------------------
target: kbusmodbusslave.compile
-------------------------------

make[1]: Entering directory &apos;/home/user/wago/ptxproj/platform-wago-pfcXXX/build-target/kbusmodbusslave&apos;
Package wago_diagnostic was not found in the pkg-config search path.
Perhaps you should add the directory containing `wago_diagnostic.pc&apos;
to the PKG_CONFIG_PATH environment variable
No package &apos;wago_diagnostic&apos; found
arm-linux-gnueabihf-gcc -c -Wall -Wextra -Os -I/home/user/wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/include/OsLinux/ -I/home/user/wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/include/dal/  -I/home/user/wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/include/diagnostic/ -DVERSION=\&quot;1.3.0\&quot; main.c -o main.o
In file included from main.c:27:0:
modbus.h:5:27: fatal error: modbus/modbus.h: No such file or directory
compilation terminated.
make[1]: *** [main.o] Error 1
Makefile:46: recipe for target &apos;main.o&apos; failed
make[1]: Leaving directory &apos;/home/user/wago/ptxproj/platform-wago-pfcXXX/build-target/kbusmodbusslave&apos;
/home/user/wago/ptxproj/rules/kbusmodbusslave.make:46: recipe for target &apos;/home/user/wago/ptxproj/platform-wago-pfcXXX/state/kbusmodbusslave.compile&apos; failed
make: *** [/home/user/wago/ptxproj/platform-wago-pfcXXX/state/kbusmodbusslave.compile] Error 2
</pre> 

What is the wago_diag package ? 
how do I include it ?
also in the source files it seem there is a lots of file with the include modbus/modbus.h
But there is no modbus folder ...

**Comment by Thomas-Brandt** [comment]
Hi,

seams a little bit strange, but I thing this is caused by changing the default ptxdist configuration you made. Aren't you?

I made a simple patch which might fix the issue.
Please test and come back.
Thanks.

[0001-Kbusmodbusslave-Added-dependency-libmodbus-to-rule-f.txt](https://github.com/WAGO/pfc-howtos/files/3616960/0001-Kbusmodbusslave-Added-dependency-libmodbus-to-rule-f.txt)

**Comment by Ekristoffe** [comment]
Hello
I have worked out why i had problem,
In order to successfully build a package we must use the ptxdist go function to buid all the other dependencies.
If not those need to be in the file.
And yes I think by default adding the dependencies is a good idea.
I will try again on a fresh ubuntu with only dependencies added to the .in file.
Ps as for now i was usigt ubuntu 16 lts but i will also try with the 18 lts.
