### ISSUE TITLE
Support for NET5 on Wago PLC

### ISSUE THREAD

**Issue by gitkrasty** [WAGO/pfc-howtos#9]
Dear, 
I have noticed a 2-year-old howto on mono and the Wago Linux PLC platform. Is there a possibility to install and run the now available NET5 runtime on the PLC? Was this scenario tested or on the other hand there is some objective that makes it impossible?
Best regards, Jan

**Comment by DirkMeihoefer** [comment]
Hello Jan,
if you have a PFC 200 G2 you could install docker and use a NET5 runtime container. For the docker installation see here: https://github.com/WAGO/docker-ipk
Best regards
Dirk

**Comment by gitkrasty** [comment]
Thank you for a quick and accurate reaction. Yes, this was one of the possibilities. Does it mean that access to the PLC interfaces (communication ports & other peripherals) must be implemented only over Ethernet and some Wago Api? Or the docker image would/can have access to some of the com ports of the PLC?

**Comment by DirkMeihoefer** [comment]
The easiest approach would be to retrieve the data from the PLC runtime via ModBus. If you don't want to have a running PLC runtime, you could use the pfc-modbus-slave image, see here: https://github.com/WAGO/pfc-modbus-slave
